kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: my-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels:
      name: deployment 
  template: 
    metadata: 
      name: testpod 
      labels: 
        name: deployment 
    spec: 
      containers: 
        - name: my-container 
          image: ubuntu 
          command: ['/bin/bash', '-c', 'while true; do echo Hello Sandeep Update; sleep 5; done']