apiVersion: v1
kind: Pod
metadata: 
  name: annotation-pod
  annotations: 
    description: "This is a annotation file"
    owner: "Sandeep"
spec: 
  containers: 
  - name: annotation-container
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo Hello Sandeep; sleep 5; done"]
  restartPolicy: Never
