kind: ReplicaSet 
apiVersion: apps/v1 
metadata:  
  name: rc-set
spec: 
  replicas: 3 
  selector: 
    matchExpressions:
      - {key: name, operator: In, values: [Sandeep, Test]}
      - {key: env, operator: NotIn, values: [production]}
  template: 
    metadata: 
      name: pod 
      labels: 
        name: Sandeep  
    spec: 
      containers: 
        - name: my-container 
          image: ubuntu 
          command: ['/bin/bash', '-c', 'while true; do echo Hello World!; sleep 5; done']