kind: ReplicationController 
apiVersion: v1 
metadata: 
  name: my-rc 
spec: 
  replicas: 2
  selector: 
    app: mmk 
  template:
    metadata: 
      name: test-pod 
      labels: 
        app: mmk 
    spec: 
      containers: 
        - name: my-container 
          image: ubuntu 
          command: ["/bin/bash", "-c", "while true; do echo Hello Sandeep; sleep 5; done"]