apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
  namespace: team-namespace
spec:
  containers:
    - name: demo-container
      image: busybox
      command: ["sh", "-c", "while true; do echo 'Running'; sleep 5; done"]
      resources:
        requests:
          memory: "64Mi"   # Guaranteed 64 MiB of memory
          cpu: "250m"      # Guaranteed 0.25 CPU
        limits:
          memory: "128Mi"  # Maximum 128 MiB of memory
          cpu: "500m"      # Maximum 0.5 CPU
