apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-quota
  namespace: team-namespace
spec:
  hard:
    pods: "10"                  # Maximum 10 pods
    requests.cpu: "2"           # Total CPU requests must not exceed 2 cores
    requests.memory: "4Gi"      # Total memory requests must not exceed 4 GiB
    limits.cpu: "4"             # Total CPU limits must not exceed 4 cores
    limits.memory: "8Gi"        # Total memory limits must not exceed 8 GiB
