apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command: ["sh", "-c", "echo 'Hello Persistent Volume' > /data/hello.txt && sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: my-storage
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
