apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command: ["sh", "-c", "env && sleep 3600"]
      envFrom:
        - secretRef:
            name: my-secret


# echo -n "Pass" | base64

# echo -n "UGFzcw==" | base64 --decode